name: Authentication Service Test
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create .env file from secret
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: Test Django Project
      run: |
        make test
      env:
        DB_NAME: test
        DB_USER: test
        DB_PASSWORD: test